version: "3"
services:
 vampi-secure:
  build: ./
  container_name: vampi-secure
  ports:
   - 8083:5000
  environment:
   - vulnerable=0

 vampi-vulnerable:
  build: ./
  container_name: vampi-vulnerable
  ports:
   - 8084:5000
  environment:
   - vulnerable=1
  volumes:
  - .:/vampi
