version: "3.8"

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./config:/app/config # Optional volume for dynamic configurations
    environment:
      - ENV=production
      - SQREEN_TOKEN=c0e73fbf154a808295f392484424abda0c430bc954959c69bc0a979bd9cfe4f1e065d67bc2fc040ee0fe2b97da9fd6c163859f889e2b3fe49834d12c8a4921b2
      - SQREEN_APP_NAME="Go DVWA"
    restart: unless-stopped
